<ul class="breadcrumb">
	<li><a href="index.php">Home</a></li>
	<li>O Apollo</li>
</ul>	

<p>O Grupo de Teatro Apollo foi criado em 1997, na aldeia de Peras Ruivas, freguesia de Seiça,concelho de Ourém, estando desde o seu início ligado ao Centro Cultural e Recreativo de Pêras Ruivas. O objetivo foi o de apresentar um espetáculo pontual, que permitisse juntar alguns jovens da aldeia e apresentá-lo à população. O texto escolhido foi a peça “Duas Gatinhas cáem casa”, um texto conhecido no âmbito do grupo de teatro da Escola Secundária de Ourém,que assim teve prossecução neste projeto. O espetáculo foi apresentado em Março de 1997, no Centro Cultural e Recreativo de Pêras Ruivas.</p>

<p>O grupo continuou a manter a regularidade de apresentar um espetáculo anual, tendo atualmente 19 anos de existência. Em 2006, o Grupo de Teatro iniciou uma residência de espetáculos no Torreão Sul do Castelo de Ourém, como em vários espaços do Castelo, permitindo desta forma, contacto com o ambiente natural daquele espaço. O primeiro de espetáculo apresentado no Torreão do Castelo de Ourém foi “O Principezinho”. Seguiram-se “Meta a menina para dentro”; “Leandro, Rei de Helíria”; “Na Terra dos Sonhos”, “Jantar de Idiotas”, “Que Farei com este Livro?” de José Saramago. A par dos espetáculos, o objetivo é também, a promoção de parcerias com estabelecimentos comerciais da Vila Medieval de Ourém, procurando-se estreitar relações e permitindo oferecer ao público uma degustação no final do espetáculo.</p>

<p>Em 2006 foi iniciado o projeto Meia Maratona de Teatro, festival de teatro do Grupo de Teatro Apollo que conta com 10 anos de existência. São convidados a participar grupos de teatro do concelho e com os quais o Apollo mantém intercâmbio, e durante três dias, o público pode ver espetáculos que decorrem de três em três horas. A juntar ao teatro, a Meia Maratona caracteriza-se pela partilha com o público das refeições. Em 2014, o festival estendeu-se para o Castelo de Ourém, sendo atualmente realizado na aldeia de Pêras Ruivas e na Vila Medieval de Ourém. Conta com 2 co-produções 2 co-produções: D. Afonso, Conde de Ourém e Príncipe de Portugal e As Memórias de Lúcia (trabalho coletivo com os grupos de teatro concelhio). É composto por 15 elementos contando entre eles, com participações assíduas, pontuais e esporádicas. Em 2011 o Grupo venceu com o espetáculo Na Terra dos Sonhos, no Festival de Proença a Nova, iniciativa promovida pela Companhia de Teatro Montes da Senhora, os prémios de melhor atriz, Tatiana Pedro, melhor ator, Paulo Santos e melhor espetáculo 2011. Foi ainda em 2011 que foi atribuído pela Câmara de Ourém ao Grupo de Teatro Apollo, através de Dora Conde, o prémio de Mérito Técnico Associativo.</p>